# Generated by Django 2.0.3 on 2022-06-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo_a',
            fields=[
                ('id_x', models.CharField(auto_created=True, max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
