# Generated by Django 2.0.3 on 2022-06-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_personinfo_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
