# Generated by Django 2.0.3 on 2022-06-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20220610_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo_b',
            fields=[
                ('id_x', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('age_x', models.BigIntegerField()),
                ('body', models.TextField(blank=True, default='', null=True)),
                ('data', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('datatime', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='')),
                ('is_true', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='personinfo_a',
            name='id_x',
            field=models.IntegerField(auto_created=True, max_length=11, primary_key=True, serialize=False),
        ),
    ]
