# Generated by Django 2.0.3 on 2022-06-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20220610_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo_a',
            name='id_x',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
